/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.TarefaController;
import Model.Projeto;
import Model.Tarefa;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author pablo
 */
public class TelaCadastroTarefa extends javax.swing.JDialog {

    TarefaController Tcontroller; 
    Projeto projeto;
    public TelaCadastroTarefa(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        EsconderCampoObrigatório();
        Tcontroller = new TarefaController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelToolBar = new javax.swing.JPanel();
        jLabelToolBarTile = new javax.swing.JLabel();
        jLabelToolBarSave = new javax.swing.JLabel();
        jPanelTarefa = new javax.swing.JPanel();
        jLabelNome = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabelPrazo = new javax.swing.JLabel();
        jScrollPaneDescricao = new javax.swing.JScrollPane();
        jTextAreaDescricao = new javax.swing.JTextArea();
        jLabelDescricao = new javax.swing.JLabel();
        jLabelNotas = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaNotas = new javax.swing.JTextArea();
        jFormattedTextFieldPrazo = new javax.swing.JFormattedTextField();
        jLabelPrazoObrigatorio = new javax.swing.JLabel();
        jLabelNomeObrigatorio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 800));
        setPreferredSize(new java.awt.Dimension(474, 465));

        jPanelToolBar.setBackground(new java.awt.Color(0, 153, 102));

        jLabelToolBarTile.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelToolBarTile.setForeground(new java.awt.Color(255, 255, 255));
        jLabelToolBarTile.setText("Tarefa");

        jLabelToolBarSave.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelToolBarSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/todoapp/resources/check.png"))); // NOI18N
        jLabelToolBarSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelToolBarSaveMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelToolBarLayout = new javax.swing.GroupLayout(jPanelToolBar);
        jPanelToolBar.setLayout(jPanelToolBarLayout);
        jPanelToolBarLayout.setHorizontalGroup(
            jPanelToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelToolBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelToolBarTile, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelToolBarSave, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                .addGap(2, 2, 2))
        );
        jPanelToolBarLayout.setVerticalGroup(
            jPanelToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelToolBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelToolBarTile, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jLabelToolBarSave, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelTarefa.setBackground(new java.awt.Color(255, 255, 255));
        jPanelTarefa.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelTarefa.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelNome.setText("Nome");
        jPanelTarefa.add(jLabelNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 6, 428, 30));

        jTextFieldNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanelTarefa.add(jTextFieldNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 42, 428, 28));

        jLabelPrazo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelPrazo.setText("Prazo");
        jPanelTarefa.add(jLabelPrazo, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 278, 428, 30));

        jTextAreaDescricao.setColumns(20);
        jTextAreaDescricao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextAreaDescricao.setRows(5);
        jScrollPaneDescricao.setViewportView(jTextAreaDescricao);

        jPanelTarefa.add(jScrollPaneDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 134, 428, 138));

        jLabelDescricao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelDescricao.setText("Descrição");
        jPanelTarefa.add(jLabelDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 98, 428, 30));

        jLabelNotas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelNotas.setText("Notas");
        jPanelTarefa.add(jLabelNotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 370, 428, 30));

        jTextAreaNotas.setColumns(20);
        jTextAreaNotas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextAreaNotas.setRows(5);
        jScrollPane2.setViewportView(jTextAreaNotas);

        jPanelTarefa.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 406, 428, 209));

        jFormattedTextFieldPrazo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        jPanelTarefa.add(jFormattedTextFieldPrazo, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 314, 428, 28));

        jLabelPrazoObrigatorio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelPrazoObrigatorio.setForeground(new java.awt.Color(255, 51, 0));
        jLabelPrazoObrigatorio.setText("Campo de prazo obrigatório");
        jPanelTarefa.add(jLabelPrazoObrigatorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 348, 428, -1));

        jLabelNomeObrigatorio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelNomeObrigatorio.setForeground(new java.awt.Color(255, 51, 0));
        jLabelNomeObrigatorio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelNomeObrigatorio.setText("Campo de nome obrigatório");
        jPanelTarefa.add(jLabelNomeObrigatorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 76, 428, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelToolBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelTarefa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelTarefa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelToolBarSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelToolBarSaveMouseClicked
        // TODO add your handling code here:
        try{
            if(CampoValido()){
                Tarefa tarefa = new Tarefa();
                tarefa.setIdProjeto(projeto.getId());
                tarefa.setNome(jTextFieldNome.getText());
                tarefa.setDescricao(jTextAreaDescricao.getText());
                tarefa.setObservacao(jTextAreaNotas.getText());
                tarefa.setCompletado(false);

                // Formatador de data
                SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
                // Data formatada que será guardada no banco
                Date prazo = dateFormat.parse(jFormattedTextFieldPrazo.getText());
                tarefa.setPrazo(prazo);
                Tcontroller.cadastrar(tarefa);
                JOptionPane.showMessageDialog(this,"Tarefa salva com sucesso");
                this.dispose();
            }else{
              //  JOptionPane.showMessageDialog(this,"Preencha os campos obrigatórios antes de salvar!!");
                 EsconderCampoObrigatório();
                if(jTextFieldNome.getText().isEmpty()){
                    jLabelNomeObrigatorio.setVisible(true);
                }
                if(jFormattedTextFieldPrazo.getText().isEmpty()){
                    jLabelPrazoObrigatorio.setVisible(true);
                }
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex);
        }
    }//GEN-LAST:event_jLabelToolBarSaveMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Java swing".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroTarefa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroTarefa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroTarefa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroTarefa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaCadastroTarefa dialog = new TelaCadastroTarefa(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField jFormattedTextFieldPrazo;
    private javax.swing.JLabel jLabelDescricao;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelNomeObrigatorio;
    private javax.swing.JLabel jLabelNotas;
    private javax.swing.JLabel jLabelPrazo;
    private javax.swing.JLabel jLabelPrazoObrigatorio;
    private javax.swing.JLabel jLabelToolBarSave;
    private javax.swing.JLabel jLabelToolBarTile;
    private javax.swing.JPanel jPanelTarefa;
    private javax.swing.JPanel jPanelToolBar;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPaneDescricao;
    private javax.swing.JTextArea jTextAreaDescricao;
    private javax.swing.JTextArea jTextAreaNotas;
    private javax.swing.JTextField jTextFieldNome;
    // End of variables declaration//GEN-END:variables

    public void setProjeto(Projeto projeto) {
        this.projeto = projeto;
    }
    
    public void EsconderCampoObrigatório(){
         jLabelNomeObrigatorio.setVisible(false);
         jLabelPrazoObrigatorio.setVisible(false);
    }
    
    
    public boolean CampoValido(){
        //Se campo nome e campo prazo NÃO estiver vazio
        return (!jTextFieldNome.getText().isEmpty()) && (!jFormattedTextFieldPrazo.getText().isEmpty());
    }

    
}
