/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ProjetoController;
import Controller.TarefaController;
import Model.Projeto;
import Model.Tarefa;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import util.CelulaColunaBotaoRenderer;
import util.CelulaColunaPrazoRenderer;
import util.TarefaTableModel;

/**
 *
 * @author pablo
 */
public class TelaInicial extends javax.swing.JFrame {

    ProjetoController Pcontroller;
    TarefaController Tcontroller;
    
    DefaultListModel projetosModel; //( projetosModel ) Será o model do componente gráfico
    TarefaTableModel tarefasModel;
    
    public TelaInicial() {
        initComponents();
        
        initDataController();
        initComponentsModel();
        
        decorateTableTask();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPaneTarefa = new javax.swing.JScrollPane();
        jTableTarefa = new javax.swing.JTable();
        jPanelToolBar = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jLabelSubTitle = new javax.swing.JLabel();
        jPanelProjetos = new javax.swing.JPanel();
        jLabelProjetosTitle = new javax.swing.JLabel();
        jLabelProjetosAdd = new javax.swing.JLabel();
        jPanelTarefas = new javax.swing.JPanel();
        jLabelTarefasTitle = new javax.swing.JLabel();
        jLabelTarefasAdd = new javax.swing.JLabel();
        jPanelListaProjetos = new javax.swing.JPanel();
        jScrollPaneProjetos = new javax.swing.JScrollPane();
        jListProjetos = new javax.swing.JList<>();
        jPanel5 = new javax.swing.JPanel();
        jPanelListaVazia = new javax.swing.JPanel();
        jLabelListaVaziaIcon = new javax.swing.JLabel();
        jLabelListaVaziaTitle = new javax.swing.JLabel();
        jLabelListaVaziaSubTitle = new javax.swing.JLabel();

        jTableTarefa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTableTarefa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Descrição", "Prazo", "Tarefa Concluída"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableTarefa.setRowHeight(40);
        jTableTarefa.setSelectionBackground(new java.awt.Color(0, 153, 102));
        jTableTarefa.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableTarefa.setShowHorizontalLines(false);
        jTableTarefa.setShowVerticalLines(false);
        jTableTarefa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableTarefaMouseClicked(evt);
            }
        });
        jScrollPaneTarefa.setViewportView(jTableTarefa);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 900));
        setPreferredSize(new java.awt.Dimension(800, 900));

        jPanelToolBar.setBackground(new java.awt.Color(0, 153, 102));

        jLabelTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/todoapp/resources/tick.png"))); // NOI18N
        jLabelTitle.setText(" Todo App");
        jLabelTitle.setToolTipText("");

        jLabelSubTitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelSubTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSubTitle.setText("Anote tudo, não esqueça nada");

        javax.swing.GroupLayout jPanelToolBarLayout = new javax.swing.GroupLayout(jPanelToolBar);
        jPanelToolBar.setLayout(jPanelToolBarLayout);
        jPanelToolBarLayout.setHorizontalGroup(
            jPanelToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelToolBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSubTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelToolBarLayout.setVerticalGroup(
            jPanelToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelToolBarLayout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(jLabelTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelSubTitle)
                .addGap(25, 25, 25))
        );

        jPanelProjetos.setBackground(new java.awt.Color(255, 255, 255));
        jPanelProjetos.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelProjetosTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelProjetosTitle.setForeground(new java.awt.Color(0, 153, 102));
        jLabelProjetosTitle.setText("Projetos");

        jLabelProjetosAdd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelProjetosAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/todoapp/resources/add.png"))); // NOI18N
        jLabelProjetosAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelProjetosAddMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelProjetosLayout = new javax.swing.GroupLayout(jPanelProjetos);
        jPanelProjetos.setLayout(jPanelProjetosLayout);
        jPanelProjetosLayout.setHorizontalGroup(
            jPanelProjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProjetosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelProjetosTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jLabelProjetosAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelProjetosLayout.setVerticalGroup(
            jPanelProjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProjetosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelProjetosTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jLabelProjetosAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelTarefas.setBackground(new java.awt.Color(255, 255, 255));
        jPanelTarefas.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelTarefasTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelTarefasTitle.setForeground(new java.awt.Color(0, 153, 102));
        jLabelTarefasTitle.setText("Tarefas");

        jLabelTarefasAdd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTarefasAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/todoapp/resources/add.png"))); // NOI18N
        jLabelTarefasAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelTarefasAddMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelTarefasLayout = new javax.swing.GroupLayout(jPanelTarefas);
        jPanelTarefas.setLayout(jPanelTarefasLayout);
        jPanelTarefasLayout.setHorizontalGroup(
            jPanelTarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTarefasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTarefasTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTarefasAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelTarefasLayout.setVerticalGroup(
            jPanelTarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTarefasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTarefasTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jLabelTarefasAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelListaProjetos.setBackground(new java.awt.Color(255, 255, 255));
        jPanelListaProjetos.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jListProjetos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jListProjetos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListProjetos.setFixedCellHeight(50);
        jListProjetos.setSelectionBackground(new java.awt.Color(0, 153, 102));
        jListProjetos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListProjetosMouseClicked(evt);
            }
        });
        jScrollPaneProjetos.setViewportView(jListProjetos);

        javax.swing.GroupLayout jPanelListaProjetosLayout = new javax.swing.GroupLayout(jPanelListaProjetos);
        jPanelListaProjetos.setLayout(jPanelListaProjetosLayout);
        jPanelListaProjetosLayout.setHorizontalGroup(
            jPanelListaProjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListaProjetosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneProjetos, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelListaProjetosLayout.setVerticalGroup(
            jPanelListaProjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListaProjetosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneProjetos)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanelListaVazia.setBackground(java.awt.Color.white);

        jLabelListaVaziaIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelListaVaziaIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/todoapp/resources/lists.png"))); // NOI18N

        jLabelListaVaziaTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelListaVaziaTitle.setForeground(new java.awt.Color(0, 153, 102));
        jLabelListaVaziaTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelListaVaziaTitle.setText("Nenhuma tarefa por aqui :D");

        jLabelListaVaziaSubTitle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelListaVaziaSubTitle.setForeground(new java.awt.Color(153, 153, 153));
        jLabelListaVaziaSubTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelListaVaziaSubTitle.setText("clique no botão \"+\" para adicionar uma nova tarefa");

        javax.swing.GroupLayout jPanelListaVaziaLayout = new javax.swing.GroupLayout(jPanelListaVazia);
        jPanelListaVazia.setLayout(jPanelListaVaziaLayout);
        jPanelListaVaziaLayout.setHorizontalGroup(
            jPanelListaVaziaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListaVaziaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelListaVaziaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelListaVaziaIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelListaVaziaTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelListaVaziaSubTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanelListaVaziaLayout.setVerticalGroup(
            jPanelListaVaziaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListaVaziaLayout.createSequentialGroup()
                .addGap(218, 218, 218)
                .addComponent(jLabelListaVaziaIcon)
                .addGap(18, 18, 18)
                .addComponent(jLabelListaVaziaTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelListaVaziaSubTitle)
                .addContainerGap(280, Short.MAX_VALUE))
        );

        jPanel5.add(jPanelListaVazia, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelToolBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelProjetos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelListaProjetos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelTarefas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelProjetos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelTarefas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelListaProjetos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelProjetosAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelProjetosAddMouseClicked
        // TODO add your handling code here:
        TelaCadastroProjeto telacadastroprojeto = new TelaCadastroProjeto(this,true);
        //Deixa a telacadastroprojeto visível 
        telacadastroprojeto.setVisible(true);
        
        //Cria um ouvinte para a janela (telacadastroprojeto) para avisar quando a janela for fechada
        telacadastroprojeto.addWindowListener(new WindowAdapter(){
            public void windowClosed(WindowEvent ev){
                //Carrega o JList com os arquivos do banco
                carregarProjetos();
            }
        });
    }//GEN-LAST:event_jLabelProjetosAddMouseClicked

    private void jLabelTarefasAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTarefasAddMouseClicked
        //Cria nova tela de cadastro de tarefa
        TelaCadastroTarefa telacadastrotarefa = new TelaCadastroTarefa(this,true);
        
        //Pega a posição do projeto selecionado na lista
        int projetoIndex = jListProjetos.getSelectedIndex();
        //Pega o projeto na lista de projetos na posição que pegamos
        Projeto projeto = (Projeto) projetosModel.get(projetoIndex);
        //Seta o projeto da tela de tarefas
        telacadastrotarefa.setProjeto(projeto);
        //Mostra a tela ao usuário
        telacadastrotarefa.setVisible(true);
        
        
        telacadastrotarefa.addWindowListener(new WindowAdapter(){
            public void windowClosed(WindowEvent ev){
                 int projetoIndex = jListProjetos.getSelectedIndex();
                 Projeto projeto = (Projeto) projetosModel.get(projetoIndex);
                 carregarTarefas(projeto.getId());
            }
        });
    }//GEN-LAST:event_jLabelTarefasAddMouseClicked

    private void jTableTarefaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTarefaMouseClicked
        //RowAtPoint: diz qual a linha clicada em uma coordenada (X,Y) do mouse
        int rowIndex = jTableTarefa.rowAtPoint(evt.getPoint());
        int columnIndex  = jTableTarefa.columnAtPoint(evt.getPoint());
        //Pega a tarefa clicada apartir da lista
        Tarefa tarefa = tarefasModel.getTarefas().get(rowIndex);
        
        /*
            Quando o evento acontecer na coluna 3 ( tarefa concluída ), usando o
            getTarefas do tarefasModel iremos pegar a lista toda e procurar a 
            tarefa na posição rowIndex e atualizar o banco com os dados atuais
        */
        switch(columnIndex){
            case 3:
                Tcontroller.atualizar(tarefa);
                break;
            case 4:
                break;
            case 5:
                
                //Remove a tarefa do banco de dados
                Tcontroller.removerPorId(tarefa.getId());
                //Remove a tarefa da lista
                tarefasModel.getTarefas().remove(tarefa);
               
                //Recarrega a lista de tarefas do projeto selecionado
                int projetoIndex = jListProjetos.getSelectedIndex();
                Projeto projeto = (Projeto) projetosModel.get(projetoIndex);
                carregarTarefas(projeto.getId());
                break;
        }
        
    }//GEN-LAST:event_jTableTarefaMouseClicked

    private void jListProjetosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListProjetosMouseClicked
        //retorna o index(posição) do projeto selecionado da nossa LISTA de projetos
        int projetoIndex = jListProjetos.getSelectedIndex();
        // Pegamos a nossa lista de projetos e procuramos o projeto na posição
        // index
        Projeto projeto = (Projeto) projetosModel.get(projetoIndex);
        //Envia como parâmetro o id do projeto selecionado da nossa lista
        carregarTarefas(projeto.getId());
    }//GEN-LAST:event_jListProjetosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Java swing".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelListaVaziaIcon;
    private javax.swing.JLabel jLabelListaVaziaSubTitle;
    private javax.swing.JLabel jLabelListaVaziaTitle;
    private javax.swing.JLabel jLabelProjetosAdd;
    private javax.swing.JLabel jLabelProjetosTitle;
    private javax.swing.JLabel jLabelSubTitle;
    private javax.swing.JLabel jLabelTarefasAdd;
    private javax.swing.JLabel jLabelTarefasTitle;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JList<String> jListProjetos;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelListaProjetos;
    private javax.swing.JPanel jPanelListaVazia;
    private javax.swing.JPanel jPanelProjetos;
    private javax.swing.JPanel jPanelTarefas;
    private javax.swing.JPanel jPanelToolBar;
    private javax.swing.JScrollPane jScrollPaneProjetos;
    private javax.swing.JScrollPane jScrollPaneTarefa;
    private javax.swing.JTable jTableTarefa;
    // End of variables declaration//GEN-END:variables
    
    public void decorateTableTask(){
        //Customizando o Header da table de tarefas
        jTableTarefa.getTableHeader().setFont(new Font ("Segoe UI",Font.BOLD,14));
        jTableTarefa.getTableHeader().setBackground(new Color(0, 153, 102));
        jTableTarefa.getTableHeader().setForeground(new Color(255, 255, 255));
        
        //Criando um sort automática para as colunas da table
        jTableTarefa.setAutoCreateRowSorter(true);
        
        jTableTarefa.getColumnModel().getColumn(2)
                .setCellRenderer(new CelulaColunaPrazoRenderer());
        
         jTableTarefa.getColumnModel().getColumn(4)
                 .setCellRenderer(new CelulaColunaBotaoRenderer("edit"));
         jTableTarefa.getColumnModel().getColumn(5)
                 .setCellRenderer(new CelulaColunaBotaoRenderer("delete"));
    }
    
    public void initDataController(){
        Pcontroller = new ProjetoController();
        Tcontroller = new TarefaController();
    }
    
    
    public void initComponentsModel(){
        // Iniciando o projetoModel, responsável por gerenciar a parte visual do JList
        projetosModel = new DefaultListModel();
        //Carrega os dados do banco para dentro desse projetoModel para exibir os dados
        carregarProjetos();
        
        tarefasModel = new TarefaTableModel();
        jTableTarefa.setModel(tarefasModel);
        
        //Se a lista de projetos estiver cheia
        if(!projetosModel.isEmpty()){
            //Deixa selecionado o primeiro projeto da lista 
            jListProjetos.setSelectedIndex(0);
            //Pega o primeiro projeto da nossa lista e guarda em projeto
            Projeto projeto = (Projeto) projetosModel.get(0);
            //Envia como parâmetro o id do primeiro projeto da lista
            carregarTarefas(projeto.getId());
        }
    }
    
    private void mostrarjTableTarefa(boolean temTarefa){
        if(temTarefa){
            //Existem tarefas
            if(jPanelListaVazia.isVisible()){
                jPanelListaVazia.setVisible(false);
                jPanel5.remove(jPanelListaVazia);
            }
            
            jPanel5.add(jScrollPaneTarefa);
            jScrollPaneTarefa.setVisible(true);
            jScrollPaneTarefa.setSize(jPanel5.getWidth(),jPanel5.getHeight());
            
        }else{
            //Não existem tarefas
            if(jScrollPaneTarefa.isVisible()){
                jScrollPaneTarefa.setVisible(false);
                jPanel5.remove(jScrollPaneTarefa);
            }
            
            jPanelListaVazia.setVisible(true);
            jPanelListaVazia.setSize(jPanel5.getWidth(),jPanel5.getHeight());
            jPanel5.add(jPanelListaVazia);
        }
    }
 
    public void carregarProjetos(){
        //Usa o ProjetoController para pegar todos os projetos do banco e guardar nessa lista de projeto
        List<Projeto> projetos = Pcontroller.buscarTodos();
        //Limpa a JList caso haja algum dado lá dentro, para deixar a JList vazia
        projetosModel.clear();
        
        for(int i = 0; i < projetos.size(); i++){
            
            //Pega um projeto da nossa lista na posição i e guarda em um projeto
            Projeto projeto = projetos.get(i);
            //Adiciona cada projeto da lista na JList
            projetosModel.addElement(projeto);
        }
        
        
        jListProjetos.setModel(projetosModel);
    }
    
    public void carregarTarefas(int idProjeto){
        List<Tarefa> tarefas = Tcontroller.buscarTodos(idProjeto);
        tarefasModel.setTarefas(tarefas);
        
        //Verifica se a lista de tarefas está cheia, se tem algo guardado
        mostrarjTableTarefa(!tarefas.isEmpty());
    }
}
